name: zone
description: "A new Flutter project."
publish_to: "none"
version: 1.7.2+431

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  rwkv_mobile_flutter:
    path: ../rwkv_mobile_flutter
#    git:
#      url: https://github.com/MollySophia/rwkv_mobile_flutter
#      ref: dev

  photo_viewer:
    git:
      url: https://github.com/HaloWang/photo_viewer
      ref: main

  adaptive_dialog: ^2.4.1
  audioplayers: ^6.4.0
  background_downloader: ^9.2.2
  collection: ^1.19.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_picker: ^10.1.9
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.7+1
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  gaimon: ^1.4.1
  gal: ^2.3.1
  go_router: ^15.1.2
  halo: ^1.0.0
  halo_alert: ^1.0.0
  halo_state: ^1.0.0
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  record: ^6.0.0
  sentry_flutter: ^8.14.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  system_info2: ^4.0.0
  url_launcher: ^6.3.1
  vclibs: ^0.1.3
  sprintf: ^7.0.0
  pretty_qr_code: ^3.4.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  icons_launcher: ^3.0.1
  json_serializable: ^6.9.5
  riverpod_lint: ^2.6.5
  sentry_dart_plugin: ^2.4.1
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - assets/lib/chat/
    - assets/model/chat/
    - assets/config/chat/
    - assets/img/chat/
    - assets/lib/qnn/
    - demo-config.json
    - .env
    - assets/filter.txt

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: zh_Hans # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/gen # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: rwkv0
  org: ce-wang
