name: tools
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

# Add regular dependencies here.
dependencies:
  crypto:
  flutter:
    sdk: flutter
  http:
  lua_dardo_co: ^0.0.10
  meta:
  path: ^1.8.0
  image: ^4.0.0
  local_web_search:
    path: ../packages/local_web_search
  zone:
    path: ..

dependency_overrides:
  proxy_setting_android:
    git:
      url: https://github.com/dengzii/proxy_setting.git
      path: packages/proxy_setting_android
      ref: main
  rwkv_downloader:
    git:
      url: https://github.com/RWKV-APP/rwkv_downloader.git
      ref: v1
  rwkv_mobile_flutter:
    path: ../../rwkv_mobile_flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
