# Debug signing configuration
debug.storeFile=debug.keystore
debug.storePassword=android
debug.keyAlias=androiddebugkey
debug.keyPassword=android

# Release signing configuration
release.storeFile=release.keystore
release.storePassword=rwkvapp123
release.keyAlias=rwkvapp
release.keyPassword=rwkvapp123
